import '../styles/globals.css'
import Head from 'next/head'
import Link from 'next/link'

function MyApp({ Component, pageProps }) {
  return (
    <>
     <Head>
        <title>NFT MARKETPLACE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <nav className='h-12 flex items-center justify-between px-5 bg-black text-gray-100'>
        <section>CDL_WAVE</section>
        <section className=' w-7/12 flex justify-evenly bg-gray-500'>
          <Link  href='/'><span className='w-2/12 bg-red-400 flex justify-center cursor-pointer'>Home</span></Link>
          <Link href='/Collection'><span className='w-2/12 bg-red-400 flex justify-center cursor-pointer'>My Collection</span></Link>
          <Link href='/Mint'><span className='w-2/12 bg-red-400 flex justify-center cursor-pointer'>Mint</span></Link>
          <Link href='/Stats'><span className='w-2/12 bg-red-400 flex justify-center cursor-pointer'>My stats</span></Link>
        </section>
        <section>DM</section>
      </nav>
      <Component {...pageProps} />
    
    </>
  )
  
}

export default MyApp
